### ISSUE TITLE
Social media button spanning

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1675-project-1#6]
Hi Thomas,

I've been trying to fix an issue I have with the way my social media buttons span at the largest size screen. They span side-by-side as wanted from approximately 610-960 px, and then jump back to being two above and two below. Any suggestions on how to fix this? Thank you!

@thomasjbradley

**Comment by thomasjbradley** [comment]
In the CSS, the 60em media query, the width of the images themselves is set to 40%, here:
https://github.com/kaybow/dsn1675-project-1/blob/gh-pages/css/main.css#L168

That won't allow them all to fit across, they'd need to be 25% or less.

**Comment by kaybow** [comment]
Thank you!
